### ISSUE TITLE
Comparison with countrycode?

### ISSUE THREAD

**Issue by briatte** [alistaire47/passport#5]
https://github.com/vincentarelbundock/countrycode

Ping @vincentarelbundock

**Comment by vincentarelbundock** [comment]
Well, I see some good ideas here, and ``passport`` made me discover the CLDR names, for which I am grateful (available in the latest version of ``countrycode`` on Github).

However, I don't really get why there needs to be a different package. 

As far as I can tell, there's isn't much new here. A couple new codes are supported, perhaps? But if that's the added value, I feel like the community would be better served by simply adding those to ``countrycode``, which has already been downloaded tens of thousands of times on CRAN.

The other function that seems original is the function that shortens long country names. That seems pretty small to me now that `countrycode` supports CLDR codes. If there's an argument that short country names are super useful, it would be trivial to add something like that directly to ``countrycode``.

The work intensive part of ``countrycode`` was not to add codes or to write tiny convenience functions, but to write a bunch of regexes, and to test them rigorously to ensure that different country name variants are correctly detected. The rest is pretty trivial IMHO.

The less generous view of ``passport`` is that it free rides on that (large) effort, and contributes little back.

Of course, this all free software, so whatever... Fork the regexes and put your name on them.

But yeah, I slept 2 hours last night, am waiting in a crappy airport lounge, and I feel cranky right now, so that probably affects my judgement.

**Comment by briatte** [comment]
If I may, @vincentarelbundock, that is a bit cranky indeed 😛 

Dear @alistaire47 – May I suggest trying to merge the code base with `countrycode` at some point? I'm a heavy user of "country code" packages in both R and Stata, and the better this job can be, the happier I am.

(Disclosure: I have made minor contributions to the package, and still want to contribute French regex in the future.)

**Comment by alistaire47** [comment]
I talked with @cjyetman about this on Twitter a while ago (CJ, apologies if I misrepresent anything; please correct), and mentioned that I was open to merging. The biggest difference at that point was a focus on presentation-ready names, which is why CLDR was so helpful. That conversation was what sparked his CLDR PR to `countrycode`, so that difference is more minimal now—there are a couple other name sets, but CLDR is likely sufficient for most situations.

That said, there are more differences, some of which he thought were unlikely to be merge-able. Aside from the differences in API structure, the biggest one is the ability to use geocoding web APIs to parse any unique location, which due to the power of the APIs allows parsing names in of lots of languages, or even addresses or distinct place names. They're a little overly-flexible, as they'll try to locate places for which they should just return `NA`, but I'm convinced it's still a valuable approach.

A more minor one is a constructor in the vein of `scales` that allows last-minute conversion of codes to names in ggplot or the like. At this point it's a thin wrapper of `as_country_name`, though, so it wouldn't be that hard for users to rewrite if they were so inclined.

A couple of the API differences are significant: I think it's important to separate parsing and conversion into separate functions (particularly if parsing involves web API calls), as they do different things. `as_country_name` is vectorized across its `short` and `variant` parameters in case a user wants "Czech Republic" instead of "Czechia", but doesn't want "Congo (Republic)". Factors are handled more explicitly. There are limitations, too: `passport` can't handle custom dictionaries or matches.

I'd like `passport` to go beyond where it currently is, too; see the previous issues for preliminary thoughts if you're curious. I'm currently working on handling country groupings more efficiently. Exactly what this will look like isn't fully baked, but at a minimum it will allow a quick call to generate a vector of a grouping, e.g. OECD countries, which can be used for subsetting or whatnot. I'd like to handle regions (at least continents and UN-defined regions) better too, though they're a little more complicated. Ultimately I'd also like to support ISO 3166-2 (states/provinces/prefectures/etc.), as well. This is currently viable for codes and ISO names (mostly in local languages, I think), but I haven't found any translations yet, which would be really nice (though a huge job to produce/standardize).

So that's where I'm at at the moment. Thoughts are welcome.

**Comment by briatte** [comment]
Many good ideas above, looks promising!

**Comment by cjyetman** [comment]
To be clear, my indication that certain things were ‘un-mergable’ was not definitive, it was just my personal assessment of how those features would fit in with the existing `countrycode` package (that's **not** to say that I feel misrepresented @alistaire47). I think the google and dstk hookup is cool and probably useful under certain conditions, but because they require an external api and they sometimes give weird results, I didn't think they would fit well since `countrycode` strives to give a very robust, always 'correct' answer, even when it's annoying. Some of the other 'API differences' I still don't really understand the usefulness of, like the `ggplot` scales thing that converts country names on the fly... personally I would just always convert the names before passing the data to `ggplot`, but I get it that different people have different workflows.

I do strongly agree with @vincentarelbundock that the vast majority of the value of `countrycode` lies in its regex set (which I had no part in other than a few edits here and there), and the rest from the meticulous collection of country code sets from original sources. The functions/methods that access them are trivial. With that in mind, if `passport` were to become significantly popular, and consequently the usage of `countrycode` went down, then there would be reduced incentive to work on `countrycode` which provides the bulk of the value (the regexes). That would be an unfortunate result for the greater good.

I think it would be feasible (even if not acceptable to @alistaire47) to make `passport` a collection of functions that wrap around `countrycode` when needed, importing `countrycode` and letting it do the conversion. That way `countrycode` retains its position as the go-to for country code conversion, and `passport` could be a collection of cool adds-on to that. I would be happy to contribute here to make that happen.

I also have a package [`memberstates`](https://github.com/cjyetman/memberstates) that aims to provide sets of countries that belong to various groupings. It's super minimal and doesn't contain too many groups yet, but it makes it easy to do things like...
```r
df %>% filter(Country.Code %in% memberstates$eu$iso3c)
```
As with `countrycode`, the value with that lies in the meticulous collection of information... the method/s of using it are trivial, and one could easily write wrappers around that underlying data also if they preferred something like...
```r
df %>% filter(member_of(country, oecd))
```

@alistaire47 if you could make some clear examples, ideally with some real or pseudo-code, of what some of these differences are, I'd be happy to review them, suggest ways that they could easily be done with `countrycode` or be added on as features to `countrycode`, or give my thoughts on how they could be written into `passport` as wrappers around `countrycode`

At a minimum, I think it would be nice if you would consider adding `countrycode` to your Imports and using the `countrycode::codelist` directly if possible... at least then `countrycode` is still getting installed, and you will benefit from having/using the most up-to-date country code list without having to update your package also.

Otherwise, your external API matching functions are completely self-sufficient, and one could use them to match a bunch of messy strings, and then use countrycode to convert to whatever code system they want.

**Comment by vincentarelbundock** [comment]
@alistaire47 let me first apologize for the tone of my previous message. That was over the line. We're all working on free projects to hell others so it's all cool. (Can you tell I slept on the plane ride?)

With respect to splitting parsing and converting, I'm not averse to the idea. The main countrycode function is getting a bit unwieldy, and it's often useful to break off reusable sub functions, if only for clarity.

Ill look at your scales example as I'm not 100% sure of what the deal is with that.

The API calls too Google maps and others are actually really cool. Sorry I had missed that in my first look. I think this is a function that my own target audience may find useful. I can totally see including this functionality as a separate function in the package (`geocode`) that would guess the place based on a string and return a tidy data frame with whatever other info Google supplies. Obviously, that would require no change to the structure of countrycode, and everyone who downloads it would get easy access.

In any case, I will think about this more in the next few days.

And let me say again that I regret if acting like ass turned you off of future collaboration.

Best,

Vincent

**Comment by vincentarelbundock** [comment]
And that's "help" not "hell" (mobile won't let me edit).

**Comment by briatte** [comment]
Brilliant, that's exactly the kind of discussion I was hoping to launch by opening the issue.

Quick comment:

> Some of the other 'API differences' I still don't really understand the usefulness of, like the `ggplot` scales thing that converts country names on the fly... personally I would just always convert the names before passing the data to `ggplot`

I haven't used that function yet, but I really like the idea. To me, it shares some similarity with `scales::percent_format`, but for countries.

Re: merging packages, I now get the point about the API/geocoding functionality.

Also, @cjyetman, `memberstates` looks great. This is typically the kind of code that almost every country-level analyst has written at least once, really. @ChristopherGandrud has coded some similar stuff [for Stata](https://github.com/christophergandrud/Country-Name-Standardizer) and [for R](https://github.com/christophergandrud/eu_members) (focusing on the EU; see also his [list of Eurozone members](https://github.com/christophergandrud/euro_membership)).

There is quality data and a good deal of effort in all three packages mentioned in this conversation – `countrycode`, `passport` and `memberstates`. It'd be great if we could find a way to advertise it to all their current and potential users: users of `countrycode` like me might enjoy learning bout the geocoding capabilities and plotting helpers of `passport`. `Suggests`, perhaps?

Thanks again to all for an interesting chat.

**Comment by cjyetman** [comment]
Well, that's 2x👍🏼 and 1x👎🏻 for the `ggplot` scale formatting, so I'm outnumbered so far 😉. However, that could easily be achieved in `countrycode` with something as simple as
```r
country_format <- function(x, ...) { countrycode(x, ...) }
```

**Comment by briatte** [comment]
Just checked the package again after several years, and it seems to have gained several "parse" functions that distinguish it from `countrycode`. This issue can likely be closed.
